### ISSUE TITLE
Redundant with ExtCore ?

### ISSUE THREAD

**Issue by nestordemeure** [DotNetKit/DotNetKit.FSharp#1]
Isn't DotNetKit.FSharp mostly redundant with [ExtCore](https://github.com/jack-pappas/ExtCore) ? It also provides wrappers for parts of the .NET standart API such as the [String module](https://github.com/jack-pappas/ExtCore/blob/master/ExtCore/String.fs).

**Comment by vain0** [comment]
Thank you for your information. I didn't know it.
